version: "3.9"
services:
  app:
    image: fotofaces.azurecr.io/fotofaces-app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - api-database

  api-database:
    image: fotofaces.azurecr.io/restapianddb-pi-project
    build: ../APIs/.
    container_name: api
    hostname: api
    ports:
      - "8393:8393"
